### ISSUE TITLE
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\acer/.cache\\torch\\hub\\master.zip'

### ISSUE THREAD

**Issue by AbinJilson** [ovh/ai-training-examples#43]
when I run app.py I'm getting this error .can you help me to fix this?

**Comment by MathieuBsqt** [comment]
Hi @AbinJilson 

Thank you for trying our application.

When you tested the application (June 2022), the app was still in beta. Not surprisingly, you encountered an error. 

Could you please try again now, to see if you still encounter an error? 
If so, please describe it more explicitly so we can help you.

**Comment by MathieuBsqt** [comment]
This issue has been closed due to inactivity. If you believe it is still relevant, please leave a comment below.
