### ISSUE TITLE
Example DockerFile

### ISSUE THREAD

**Issue by mpariente** [ovh/ai-training-examples#61]
Hello, 

Great resources here ! 

Could you share the DockerFile you used for this example please ? 

Or maybe to generate [this image](https://hub.docker.com/r/ovhcom/ai-training-pytorch) ? 

Thank you in advance !
Manu

**Comment by eleapttn** [comment]
Hello Manu, 

This Docker image will be updated soon (at the beginning of 2023). 
Moreover, the Dockerfiles will be open-sourced in 2023! We will get back to you shortly.

Sincerely,

Eléa from OVHcloud's AI Solutions team

**Comment by MaximeWeyl** [comment]
@mpariente : if you want, you can also use the dockerfiles here, which are the one that will be open sourced in 2023. They lack proper documentation and will continue to evolve before official open sourcing, but they are a good starting point !

https://github.com/MaximeWeyl/ai-images-sources
