### ISSUE TITLE
llama2-fine-tuning/llama_2_finetuning.ipynb run into errors

### ISSUE THREAD

**Issue by RocketStar** [ovh/ai-training-examples#88]
I tried to run the notebook on my Local server with a 3060 GPU.  It run into the following error

`---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[15], line 4
      2 model_name = "meta-llama/Llama-2-7b-hf" 
      3 bnb_config = create_bnb_config()
----> 4 model, tokenizer = load_model(model_name, bnb_config)

ImportError: Using `load_in_8bit=True` requires Accelerate: `pip install accelerate` and the latest version of bitsandbytes `pip install -i https://test.pypi.org/simple/ bitsandbytes` or pip install bitsandbytes` 
`

**Comment by MathieuBsqt** [comment]
Hi @RocketStar 
The error message you are facing indicates that `accelerate` and `bitsandbytes` libraries are not installed on your system, which is causing the `ImportError`. `bitsandbytes` may be installed but not up to date.

Did you execute the  `pip install -r requirements.txt` command correctly? If the `bitsandbytes` is installed, can you update it to its latest version via pip ? 

(The `requirements.txt` includes the libraries you need to install to make the notebook work. This file is included in the repository [link here](https://github.com/ovh/ai-training-examples/blob/main/notebooks/natural-language-processing/llm/miniconda/llama2-fine-tuning/requirements.txt)

You can also install each library separately by running:
`pip install git+https://github.com/huggingface/accelerate.git`
`pip install --upgrade bitsandbytes` 

This will update the `bitsandbytes` library to its latest version.

After installing these libraries, **make sure to restart your Python environment or kernel** to ensure they are properly loaded. Then, you should be able to run your code without encountering this `ImportError`.

**Comment by MathieuBsqt** [comment]
This issue has been closed due to inactivity for 30 days. If you believe it is still relevant, please leave a comment below.
